# Generated by Django 3.0 on 2024-12-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergnecynumber',
            name='relation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
