# Generated by Django 3.0 on 2024-12-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emergnecynumber_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergnecynumber',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
