# Generated by Django 3.0 on 2025-10-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20251014_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='FROM',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='TO',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='PINKPOLICE',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='dangerousspot',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='EmergancyAssist',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='location',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='pinkpolice',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='pinkpolice',
            name='POLICESTATION',
        ),
        migrations.DeleteModel(
            name='SafePoint',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='visuals',
            name='USER',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='DangerousSpot',
        ),
        migrations.DeleteModel(
            name='EmergencyRequest',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PinkPolice',
        ),
        migrations.DeleteModel(
            name='PoliceStation',
        ),
        migrations.DeleteModel(
            name='SubAdmin',
        ),
        migrations.DeleteModel(
            name='Visuals',
        ),
    ]
