# Generated by Django 3.0 on 2025-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pinkpolice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinkpolice',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pinkpolice',
            name='vechileno',
            field=models.CharField(max_length=100),
        ),
    ]
