# Generated by Django 3.0 on 2025-12-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
            ],
        ),
    ]
